// <auto-generated />
namespace MvcMovie.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Rating1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rating1));
        
        string IMigrationMetadata.Id
        {
            get { return "201912081834514_Rating1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
